#!/bin/bash

# Ths script is part of the contextualization file. It 
# copies the source code on the VM, unpacks it, and sets
# the PYTHONPATH environment variable. 

# Is filled in by the frontend
FRONTEND=%FRONTEND_URL%
SOURCE=$FRONTEND/download
ROOT_DIR=/root
CPS_HOME=$ROOT_DIR/ConPaaS

LOG_FILE=/var/log/cpsmanager.log
ETC=/etc/cpsmanager
VAR_TMP=/var/tmp/cpsmanager
VAR_CACHE=/var/cache/cpsmanager
VAR_RUN=/var/run/cpsmanager

export PYTHONPATH=$CPS_HOME/src/:$CPS_HOME/contrib/

/etc/init.d/memcached start
/usr/bin/scalarisctl -d -f -s start

# Enable GIT-based code uploads
. $CPS_HOME/scripts/manager/default-git-deploy-hook 

$CPS_HOME/sbin/manager/php-cpsmanager -p 80 -c $CPS_HOME/manager-config.cfg -t $CPS_HOME/state.pickle -m $CPS_HOME/crt_state.txt 1>$ROOT_DIR/manager.out 2>$ROOT_DIR/manager.err &
manager_pid=$!
echo $manager_pid > $ROOT_DIR/manager.pid
